install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: TastyDomainDriven.sln

after_build:
  - cmd: ECHO nuget pack TastyDomainDriven\TastyDomainDriven.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack TastyDomainDriven\TastyDomainDriven.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: ECHO nuget pack TastyDomainDriven.Azure\TastyDomainDriven.Azure.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -IncludeReferencedProjects
  - cmd: nuget pack TastyDomainDriven.Azure\TastyDomainDriven.Azure.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -IncludeReferencedProjects